# Pipeline to check if gradle builds before merge_request_event.

image: mobiledevops/android-sdk-image:34.0.1

variables:
  ANDROID_PROJECT_DIR: "frontend"   
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g'"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - frontend/.gradle/
    - frontend/.gradle/caches/
    - frontend/.gradle/wrapper/

before_script:
  - cd "$ANDROID_PROJECT_DIR"
  - chmod +x gradlew

build_android_debug: # Build
  stage: build
  tags:
    - dind # docker-in-docker runner
  script:
    - ./gradlew clean
    - ./gradlew assembleDebug --stacktrace --no-daemon -x test
  only:
    - merge_request

test_android_unit: # Unit test
  stage: test
  tags:
    - dind # docker-in-docker runner
  script:
    - ./gradlew testDebugUnitTest --stacktrace --no-daemon
  only:
    - merge_requests