services:
    backend: 
      build: .
      container_name: backend
      restart: always
      expose:
        - "${PORT}"
      env_file:
        - .env
      networks:
        - app-network

    caddy:
      image: caddy:latest
      container_name: caddy
      restart: unless-stopped
      ports:
        - "80:80"   # public HTTP port - required to have a http
        - "443:443" # public HTTPS port - encrypted traffic
      environment:
        - PORT=${PORT}
        - HOST=${HOST}
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./certs:/etc/certs # moving over the certificate
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - backend
      networks:
        - app-network
   
networks:
  app-network:
volumes:
  caddy_data:
  caddy_config:
    
